from pathlib import Path

from .assurance import assure
from .storage import read_yaml


def _items(values):
    return ", ".join(str(v) for v in values) if values else "—"


def _reviews(values):
    if not values:
        return "—"
    rendered = []
    for review in values:
        if not isinstance(review, dict):
            rendered.append(str(review))
            continue
        value = f"{review.get('reviewer', '?')}={review.get('status', '?')}"
        if review.get("reason"):
            value += f" ({review['reason']})"
        rendered.append(value)
    return ", ".join(rendered)


def _contract_item(value):
    if isinstance(value, dict):
        identifier = value.get("id")
        statement = value.get("statement", str(value))
        return f"{identifier}: {statement}" if identifier else str(statement)
    return str(value)


def _trace_item(label, value):
    trace = value.get("traceability", {}) if isinstance(value, dict) else {}
    excerpt = trace.get("prompt_excerpt", "—")
    rationale = trace.get("rationale", "—")
    linked = _items(trace.get("constraint_ids", []))
    return f'{label} ← "{excerpt}" — {rationale} [Constraints: {linked}]'


def render_report(workspace: Path) -> str:
    mission = read_yaml(workspace / "mission.yaml")
    agents = read_yaml(workspace / "agents.yaml")["agents"]
    ledger = read_yaml(workspace / "ledger.yaml")
    requirements = ledger["requirements"]
    result = assure(workspace)
    rows = [
        "| ID | Requirement | Status | Owner | Acceptance | Evidence | Required Reviews |",
        "|---|---|---|---|---|---|---|",
    ]
    assumptions = [_contract_item(value) for value in ledger.get("assumptions", [])]
    risks = [_contract_item(value) for value in ledger.get("risks", [])]
    evidence, acceptance, reviews, traceability = [], [], [], []
    constraint_lines = []
    for category, values in ledger.get("constraints", {}).items():
        constraint_lines.extend(
            f"{value.get('id', '—')} [{category}]: {value.get('statement', '—')} ← \"{value.get('prompt_excerpt', '—')}\""
            for value in values if isinstance(value, dict)
        )
    clarification_lines = []
    for clarification in ledger.get("clarifications", []):
        if isinstance(clarification, dict):
            clarification_lines.append(
                f"{clarification.get('id', '—')} [{clarification.get('status', '—')}]: {clarification.get('question', '—')}"
            )
            traceability.append(_trace_item(clarification.get("id", "Clarification"), clarification))
    for req in requirements:
        rows.append(
            f"| {req.get('id', '—')} | {req.get('statement', '—')} | {req.get('status', '—')} | "
            f"{req.get('owner', '—')} | {_items(req.get('acceptance', []))} | "
            f"{_items(req.get('evidence', []))} | {_reviews(req.get('required_reviews', []))} |"
        )
        assumptions.extend(req.get("assumptions", []))
        risks.extend(req.get("risks", []))
        evidence.extend(req.get("evidence", []))
        acceptance.extend(f"{req.get('id', '—')}: {item}" for item in req.get("acceptance", []))
        reviews.append(f"{req.get('id', '—')}: {_reviews(req.get('required_reviews', []))}")
        traceability.append(_trace_item(req.get("id", "Requirement"), req))
    for value in ledger.get("assumptions", []):
        if isinstance(value, dict):
            traceability.append(_trace_item(value.get("id", "Assumption"), value))
    for value in ledger.get("risks", []):
        if isinstance(value, dict):
            traceability.append(_trace_item(value.get("id", "Risk"), value))
    bullet = lambda values: "\n".join("- " + str(v) for v in values) if values else "- None recorded"
    return f"""# Battalion Mission Report

## Mission

- **Title:** {mission['title']}
- **Objective:** {mission['objective']}
- **Mission prompt:** {mission.get('mission_prompt') or mission.get('original_prompt', '—')}
- **Mission status:** {mission['status']}

## Mission Contract

- **Generated by:** {ledger.get('generated_by', 'manual')}
- **Requirements:** {len(requirements)}
- **Assumptions:** {len(ledger.get('assumptions', []))}
- **Risks:** {len(ledger.get('risks', []))}
- **Clarifications:** {len(ledger.get('clarifications', []))}
- **Extracted constraints:** {sum(len(values) for values in ledger.get('constraints', {}).values())}

## Extracted Constraints

{bullet(constraint_lines)}

## Clarifications

{bullet(clarification_lines)}

## Prompt Traceability

{bullet(traceability)}

## Doctrine

{bullet(mission.get('doctrine', []))}

## Standing Agent Team

{bullet([a['name'] + ': ' + a['charter'] for a in agents])}

## Requirements

{chr(10).join(rows)}

## Acceptance Criteria

{bullet(acceptance)}

## Evidence Summary

{bullet(evidence)}

## Review Summary

{bullet(reviews)}

## Assumptions

{bullet(assumptions)}

## Risks

{bullet(risks)}

## Assurance Result

- **Status:** {result.status}
- **Recommendation:** {result.recommendation}
- **Confidence:** {result.confidence}

{bullet(result.findings)}

## Human Approval

Decision: PENDING

Options:
- APPROVED
- REJECTED
- ACCEPTED_WITH_RISK
- DEFERRED

Reviewer:
Date:
Notes:
"""
